firekylin/firekylin

.thinkjsrc
package.json

增加.thinkjsrc， 修复 firekylin下不能使用 `thinkjs module xxx`
fix #14

add thinkjsrc and make `thinkjs module xxx` successful

---

.gitignore
firekylin.sql
gulpfile.babel.js
install.js
package.json

增加了 `gulp release` 任务，可以将编译后的版本打包出来，去除所有开发依赖，包括 gulp, webpack, eslint, node-sass, browser-sync 等，方便用户使用。使用方法是直接 `npm run release`，即会在根目录下生成 release 文件夹，将其打包供用户下载即可。
将原来的 `gulp install` 任务单独成立一个 `install.js` 文件，因为 `release` 之后的版本去除了 `gulp` 的依赖，所以为了开发和编译后版本都方便，将其独立出来。

增加发布编译后版本任务

---

install.js

Mysql allows no user password(very common in development), therefore the install script should too.
Table prefix should also be nullable, since it's isn't in any way necessary for a working installation.

Allow empty database password and no table prefix

---

www/theme/firekylin/layout.html

Normally `zh_CN` should be `zh-CN` and `UTF-8` should be `utf-8`.

update layout of the default theme

---

src/admin/controller/api/file.js
www/static/css/admin.css
www/static/src/admin/component/import.jsx

@lizheming 之前说的导入功能（
研究了一下ghost导出的json格式，添加了这个功能，本机在dev和prod测试通过。node版本是6.9.1。
- 入口在导入设置，样式和导入wordPress一致，可能用radioGroup更好？
- 因为是json格式文件，没有引入新模块，直接利用了think.safeRequire
- Ghost博客测试了0.7+~0.8+的部分版本，高版本导出的json内容只多不少，应该没有字段错误的问题

增加从Ghost博客导入功能

---

src/admin/service/upload/local.js
src/admin/service/upload/remote.js

在实验图片上传功能时发现报错，测试发现是上传的service中local和remote用到了path相关方法，但是没有import
base中虽然有import path，但是extends的只有base export的内容，应该是这样的

fix local && remote upload without path

---

www/static/src/admin/component/options_general.jsx

最近在进行博客优化的过程中，发现有对logo图片的优化需求，有以下几种需求：
1：logo图片使用base64，基本设置页面使用img无法显示
2: logo使用cdn的处理功能，如七牛的?imageView2/0，又拍云的!xxx，img在带有?m=timestamp的情况下影响使用
改写后，基本设置的logo图采用背景图，并且在base64和使用cdn的情况下，使用不带时间戳的url，本地图片仍旧使用时间戳

update general image display

---

src/home/model/post.js

RSS页面缺失title,link,pubDate等字段，找了一下发现feedFullText不为0时field写错了导致的

修复feedFullText不为0时RSS显示问题

---

src/common/config/config.js

> Honor `PORT` environment variable as a secondary to `port` file.
> 在没有本地 `port` 文件时遵循 `PORT` 环境变量。
1. **推荐：** 在 `pm2.json` 的 `env` block 里添加 `PORT` 如下：
```json
"env": {
"PORT": 8000
}
```
2. 设置系统环境变量
Fixes #261.

遵循 PORT 环境变量

---

src/admin/service/upload/local.js
www/development.js
www/production.js
www/testing.js

Usage: 添加你的（设置好回源功能的）CDN 或者 对象存储到 `www/production.js` 如下：
`UPLOAD_URL_PATH: 'https://xxxxx.oss-cn-hongkong.aliyuncs.com'`
选择本地上传的文件将使用此域名。

Added UPLOAD_URL_PATH. 

---

src/admin/controller/api/file.js
src/admin/service/upload/base.js
src/admin/service/upload/local.js
src/admin/service/upload/remote.js
www/static/src/common/component/editor/index.jsx

`think.UPLOAD_PATH`是绝对路径, 需要把静态资源根路径替换掉, 本地亲测通过~
配置:
```
UPLOAD_PATH: path.join(__dirname, 'image')
```
生成:
```
/image/20170401/a649e147108982f283fec4c30b7c44a2.png"
```

更新抓取图片保存时路径

---

src/home/config/route.js
src/home/controller/base.js
src/home/controller/post.js

As discussed:
```
[
'options',
'navigation',
'themeConfig',
'VERSION',
'site_url',
'categories',
'currentYear'
]
```
will be present in all .json endpoints. 
Close #296 upon merge.

#296 Add JSON endpoints

---

src/admin/controller/api/post.js

在标签管理页面添加标签是没问题的, 在文章编辑页添加时被 encode 了, 导致很多地方二次 encode 时数据对不上, 比如: https://github.com/firekylin/firekylin/blob/0.15.6/src/home/model/tag.js#L48
并且浏览器会自动 decode, 这样导致获取的跟数据库内不同

修复在文章编辑页添加的标签时字段 `pathname` 被encode

---

src/home/controller/base.js
src/home/controller/index.js
src/home/controller/post.js
src/home/model/post.js
src/home/model/tag.js
www/theme/firekylin/tag.html

1. 那个最近文章我叫她 `lastPostList` 了...
1. 修改了 tag 页面内变量, 直接使用了全局的数据
1. 使用了缓存, 因为发现查询量还是很大的, 缓存时间在 [src/common/config/cache.js](https://github.com/firekylin/firekylin/blob/master/src/common/config/cache.js) 内配置了, 本地测试缓存前、缓存后 SQL 执行情况正确

添加home页面内标签列表和最近十篇文章列表数据

---

src/common/config/config.js

可以在pm2.json的env里直接设置，防止在app/common/config/config.js里修改导致更新时被覆盖的问题

新增host环境变量

---

www/theme/firekylin/res/js/firekylin.js

lazyLoadImagesp[] 为动态更新的 HTMLCollection type. 首屏多图时会导致 index 错位，所以 i 从最后一位开始遍历回 0 规避这个问题。
Reported by @xuexb .

Fix: Image Lazyload Elements Index Mismatch

---

package.json
src/common/config/config.js
yarn.lock

设置缓存控制为 public 方式，增加对中间缓存服务器的支持
（暂时无法合并，需要修改 webpack 的打包配置）

升级 ThinkJS 版本，并设置静态资源的缓存控制为 public

---

src/common/config/view.js
view/home/rss.xml

#345 
sanitize 解决方案参照 https://stackoverflow.com/questions/14665288/removing-invalid-characters-from-xml-before-serializing-it-with-xmlserializer
在 view.js 中添加 nunjucks filter xml
在 rss.html 使用 xml filt

remove invalid characters from XML in rss by add filter in nunjuncks

---

www/static/css/admin.css
www/static/src/admin/component/post_create/style.css

Let me know if this will work. #395 (1)

Updated Editor height styles. #395 (1)

---

src/common/service/marked-with-mathjax.js

修复渲染 MathJax 时，正则匹配 `lastIndex` 增量的错误
以下文本可以复现 BUG
```
`$1.6152381897$`，`$ 1.6151500386$`
```

fixed mathjax regex error

---

www/static/src/admin/component/user_create.jsx

https://github.com/firekylin/firekylin/pull/428/files#diff-154b985cfa5089c61d24436ad02588a4L120
`getProps()` is checking for `this.email` which is not set until after component rerendering from `this.setState({userInfo: data})`, therefore, moving `this.hasEmail = !!data.email` before `setState` fixes #427.

Fix #427 User Email should not be editable

---

src/admin/service/upload/qiniu.js

七牛SDK(Node.js)由v6升级到v7时，SDK中putFile的接口有变动，导致原有功能出现异常。
本次PR保留了原有的上传规则，利用七牛[上传策略](https://developer.qiniu.com/kodo/manual/1206/put-policy)中的saveKey，配置其[魔法变量](https://developer.qiniu.com/kodo/manual/1235/vars#magicvar)，上传后，保存key值规则`/{prefix}/$(year)$(mon)$(day)/$(etag)$(ext)`。

fix: 解决七牛SDK升级v7.1.*后，没有更新七牛SDK API接口的bug

---

www/static/src/components/editor/index.tsx

**Fixes**
- 修复插入超链接的错误  相关issue close #599

fix(editor): fix link-modal insert url error

---

src/admin/controller/api/file.js
src/admin/controller/api/system.js
src/home/service/comment.js

- 起因：
今天发现进入后台后系统概况信息迟迟不出现，打开控制台发现这条 system 请求耗时特别长，刷新几次都需要几十秒
- 经过：
大概是卡在了这里，获取 latest version 时间过长
https://github.com/firekylin/firekylin/blob/bd1de31eb07f959910a040471cf09356a139c388/src/admin/controller/api/system.js#L26-L34
没有触发这里设置的 defaults
https://github.com/firekylin/firekylin/blob/bd1de31eb07f959910a040471cf09356a139c388/src/admin/controller/api/system.js#L9-L13
随手翻了文档，request.defaults 返回一个新实例，不改变原对象
https://github.com/request/request#requestdefaultsoptions
- 结果：
顺手把项目里用过 request.defaults 的地方改了改

fix invalid func, request.defaults

---

www/theme/firekylin/layout.html

使用发现默认主题修改不生效，定位发现是www/theme/firekylin/layout.html中headers里的style部分由于{% %} 和{{ }} 被错误的拆解换行导致模板不能被正确解析。

修复了www/theme/firekylin/layout.html文件中的全局样式由于错误的格式化导致大括号被错误拆解并换行带来的解析错误。
