src/admin/controller/post.js
src/admin/controller/user.js
view/web/custom/navigation.html
www/index.js

[Error] Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2015-11-30T10:57:54+08:00' for column 'modify_date' at row 1

修复在mysql5.6的某些版本下date默认数据格式不对导致不能写入的问题

---

www/static/src/admin/app.jsx

```
cxys-mac:firekylin_cms app$ webpack
Hash: 3a2a01ee08b899f60413
Version: webpack 1.12.14
Time: 32980ms
Asset     Size  Chunks             Chunk Names
admin.bundle.js   312 kB       0  [emitted]  admin
common.js   673 kB       1  [emitted]  vendor
admin.bundle.js.map  1.85 MB       0  [emitted]  admin
common.js.map   4.8 MB       1  [emitted]  vendor
[0] multi vendor 124 bytes {1} [built]
+ 922 hidden modules
ERROR in ./www/static/src/admin/app.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./component/app in /Users/local/workspace/firekylin_cms/www/static/src/admin
@ ./www/static/src/admin/app.jsx 15:11-37
ERROR in ./www/static/src/admin/app.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./component/dashboard in …
```

修复react component文件名大小写

---

www/static/src/admin/component/post_create/index.jsx

修复文章推送列表不显示的问题

---

package.json

fix upload problem without upyun module

修复0.13.0版本上传缺少又拍云模块报错问题

---

src/admin/controller/api/post.js

markdownToHtml方法没有传highlight导致代码高亮失效

fix highlight not work

---

src/admin/service/import/ghost.js

修复ghost导入功能

---

src/admin/controller/api/page.js
src/admin/controller/api/post.js
src/admin/model/page.js
src/admin/model/post.js

旧的用法用一次后被清掉。
导致的bug：发帖时，如果path在page已经存在，发帖前的检测会通过，添加也提示成功，但并未创建帖子。

解决modelInstance预处理的问题

---

src/admin/controller/api/post.js
www/static/src/admin/component/options_reading.jsx
www/static/src/admin/component/post_list.jsx
www/static/src/admin/store/post.js

审核通过时可更新发帖时间

---

src/admin/controller/api/post.js
src/admin/model/post.js

Fixed a #252 bug `generateTocName` undefined

Fixed a #252 bug `generateTocName` undefined

---

www/theme/firekylin/page.html
www/theme/firekylin/post.html
www/theme/firekylin/res/js/firekylin.js

Added image lazy load to main theme

---

src/home/controller/post.js
www/theme/firekylin/index.html
www/theme/firekylin/search.html

Per @xuexb 's comment on #280 .

Added canonical url tags for home page / tag / cate & search pages

---

src/home/config/route.js
src/home/controller/index.js
www/theme/firekylin/layout.html

1. 添加`/opensearch.xml`支持, 但需要博客是 HTTPS 环境才支持(by @qgy18)
1. 把`<title>`标签往前移动, 话说我在想要不要让`keywords, description`也往前靠靠...

添加opensearch.xml支持

---

src/home/controller/base.js

Hide 'options' from json endpoints

---

src/common/config/config.js
src/home/model/post.js

1. 添加user.email
2. 用户判断`> 1`导致没有添加上`user_id`字段, 在查`user`表时为`id=undefined`了

添加user.email

---

src/admin/controller/api/user.js
src/common/config/locale/en.js
www/static/src/admin/component/post_list.jsx

1. 修复后台文章列表搜索分页
1. 优化添加用户重复时的提示

修复后台文章列表搜索分页

---

www/static/css/admin.css
www/static/src/admin/component/cate_list.jsx
www/static/src/admin/component/navigation.jsx
www/static/src/admin/component/page_list.jsx
www/static/src/admin/component/push_list.jsx
www/static/src/admin/component/tag_list.jsx
www/static/src/admin/component/user_list.jsx

Added Edit functionalities to navigation items.

---

package.json
src/admin/controller/api/base.js
src/admin/controller/api/file.js
www/static/src/admin/component/export.jsx
www/static/src/admin/component/sidebar.jsx
www/static/src/admin/page/options/export.js
www/static/src/admin/page/options/index.js

初步支持直接导出所有 Markdown 文件，使用 `jszip` 压缩成 `.zip` 文件。

add support to export Markdown files

---

src/admin/model/post.js
src/common/service/marked-with-mathjax.js
yarn.lock

修复数学表达式在表格中不生效的问题；生成文章摘要时过滤数学表达式（SVG）内容

---

src/admin/controller/api/file.js
www/static/src/admin/component/export.jsx

在 markdown 头添加 Hexo 和 Jekyll 通用的 YAML 格式的 Front Matter

导出成 Hexo / Jekyll 支持

---

www/static/css/admin.css
www/static/src/admin/component/post_create/index.jsx

Fix UI bug introduced in #354 and mentioned in #375 .

Fix #375 Clean up Radio and Checkbox styles

---

www/static/src/admin/component/options_comment.jsx

网易云跟帖 Add Deprecated Messaging

---

src/home/service/install.js

auto create database during installation. close #374 and #370 when merged!

auto create database during installation

---

www/static/src/admin/component/post_create/style.css
www/static/src/common/component/editor/style.css

Bugfix - Markdown panel height fix on drag and full screen

---

www/theme/firekylin/res/css/article.css
www/theme/firekylin/res/js/firekylin.js

过程见: https://xuexb.com/post/highlight-showline.html
可能存在的问题:
1. 代码兼容问题, 用了`map`, `querySelectorAll.forEach`
1. 实现思路问题
1. 代码量不小...

添加代码块显示行号, 添加代码块显示语言, 添加行号高亮, fix #336

---

src/home/controller/post.js
src/home/logic/post.js

Followup to #384: Update Logic Check for Post / Page Preview Feature.

---

src/admin/controller/api/post.js
src/home/controller/post.js
www/static/src/admin/component/post_create/index.jsx
www/static/src/admin/component/post_create/style.css

Added Featured Image option

---

src/admin/controller/user.js
src/admin/logic/user.js
www/static/css/admin.css
www/static/src/admin/action/user.js
www/static/src/admin/component/App.jsx
www/static/src/admin/component/login.jsx
www/static/src/admin/store/user.js

add forgot password and reset password function.

---

www/static/src/admin/component/post_create/style.css

Follow-up to #396.
不好意思 我强迫症 刚下面留白太多了。

Updated Editor heights.

---

www/theme/firekylin/res/js/firekylin.js

使用传统的`for`循环吧, 元素源都是使用`querySelectorAll`选择, 即使没有匹配也是`[]`~

修复nodeList.forEach报错

---

src/home/controller/post.js

`options.featuredImages` error on new install
#390

Featured Images Handle post.options being null

---

src/admin/service/export/hexo.js

fix hexo files export error

---

package.json

https://github.com/thinkjs/thinkjs/wiki/关于模型中-where-使用不当导致-SQL-注入的问题修复方案

ThinkJS SQL Injection Bugfix

---

www/theme/firekylin/res/js/firekylin.js

Fix lazyload scrollTop detection issue

---

package.json
src/admin/service/upload/aliyun.js
www/static/src/admin/component/options_upload.jsx

文件上传支持阿里云OSS

---

package.json
src/admin/service/upload/smms.js
src/home/service/comment.js
www/static/src/admin/component/options_upload.jsx

增加新功能, 上传图片到sm.ms 方便使用,
回报社区的圣诞礼物
后面的commit 纯属改msg和头像(刚换了电脑 git环境没配置) 😂
最后圣诞快乐 :)

[Feature] 添加上传图片 至 sm.ms图床功能

---

www/static/src/admin/component/post_create/index.jsx

Fix #466 Unable to clear featured image

---

src/home/controller/post.js

Rename template file for posts under a tag

---

Dockerfile
docker-entrypoint.sh
production.js

reason:
- release 更新不及时
- dockerhub 免费自动构建

feat: add Dockerfile

---

Dockerfile

更新 Dockerfile 构建时候的分层
- 原先将整个 context 拷贝进去再 npm install，context 有哈希变动就会重新下载 npm 包
- 现在先添加 package.json 到 /app，npm install 完了再把 context 中内容拷贝进来，这样只要 package.json 哈希没变，之后构建就会使用这一层的 cache

fix: Dockerfile, 构建时 npm 包安装尽量使用 cache

---

.prettierrc
tsconfig.json
www/static/src/App.tsx
www/static/src/components/article/article.model.ts
www/static/src/components/article/article.tsx
www/static/src/components/editor/image-modal/image-modal.tsx
www/static/src/components/editor/link-modal/link-modal.tsx
www/static/src/global.d.ts
www/static/src/routes.tsx

A little code style changes

---

www/static/src/components/article/article.store.ts
www/static/src/components/editor/index.tsx

**Fixes**
- 修复日期格式`YYYY-MM-DD`在Safari上的错误  关联Issue #591

Fix date error

---

src/admin/controller/api/options.js
view/admin/index_index.html
www/static/src/components/article/article.store.ts
www/static/src/components/editor/index.tsx
www/static/src/routes/dashboard/dashboard.tsx
www/static/src/routes/login/login.tsx
www/static/src/routes/options/upload/tencent/tencent.tsx
www/static/src/routes/options/upload/upload.enum.ts
www/static/src/routes/options/upload/upload.tsx

**Features**
- 登录页增加自动登录项
**Fixes**
- 增加重构丢失的腾讯云  关联issue #608

Add Tentect Cloud & login page remember me option

---

www/static/src/routes/options/general/general.tsx

**Fixes**
- 修复基本信息不显示的错误  相关issue #612

fix(admin/options): 修复基本信息不显示的错误

---

.gitignore
yarn.lock

**Fixes**
- Fix yarn.lock file error #624

Fix yarn.lock file error

---

www/config/paths.js
www/config/webpack.common.js
www/static/src/components/article/article.tsx

**Fixes**
- 修复新建文章会变成编辑文章的错误 #628

fix(admin/article): fix article reset error

---

.eslintrc
package.json
www/static/src/routes/appearance/theme/theme.tsx
www/static/src/routes/user/user_list/user_list.tsx
yarn.lock

**Fixes**
- Fix theme name display error
- Fix security warning (upgrade `webpack-bundle-analyzer` to latest)
**Refactor**
- User can not be deleted when the user has more than 0 articles

Fix theme name display error & forbid delete user when the user has more than 0 articles

---

www/static/src/components/article/control-public/control-public.tsx

数据库类型是 tinyint 应该是 0 和 1，目前提交的是 1 和 2

fix is_public 属性赋值错误

---

package.json
www/static/src/components/article/article.tsx
www/static/src/components/editor/index.tsx

close #422 when pr merged
只有新建文章/页面的时候启用该功能，输入标题会自动转换成拼音，只要用户手动编辑过 URL 之后，就不再做转换。

pathname pinyin convert support
